language: ruby
rvm:
- 2.1

# Assume bundler is being used, install step will run `bundle install`.
install: gem install jekyll html-proofer
script: jekyll build && htmlproof --file-ignore /services/ ./_site

# branch whitelist
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  
after_success:
  - cp ./_site/robots-surge.txt ./_site/robots.txt
  - surge --project ./_site/ --domain ssl.maxlaumeister.com

