language: ruby
rvm:
- 2.1
install:
- gem install jekyll html-proofer
- if [[ ! -f google-cloud-sdk/path.bash.inc ]]; then echo "Downloading google cloud
  sdk"; wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip -O ../gsdk.zip;
  unzip -qq ../gsdk.zip -d ..; ../google-cloud-sdk/install.sh --usage-reporting false
  --path-update false --rc-path=~/.bashrc --bash-completion false --override-components=app;
  fi;
script: jekyll build
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
after_success:
- cd ./_site
- cp ./robots-surge.txt ./robots.txt
- surge --domain ssl.maxlaumeister.com
- ../../google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ../_gapps-key.json
- mkdir static
- mv * ./static
- mv ./static/app.yaml ./app.yaml
- ../../google-cloud-sdk/bin/gcloud --project "${GAPPS_ID}" preview app deploy --quiet --set-default
  app.yaml
before_install:
- openssl aes-256-cbc -K $encrypted_2235a1d3dd99_key -iv $encrypted_2235a1d3dd99_iv
  -in _gapps-key.json.enc -out _gapps-key.json -d
