# Site settings
title: Blog - Maximillian Laumeister
description: "Notes on tech and web development by Maximillian Laumeister."
url: "http://blog.maxlaumeister.com/"
author:
  name: "Maximillian Laumeister"
  email: "max.laumeister@gmail.com"
  url: "http://www.maxlaumeister.com/"
  
analytics-id: UA-24440376-11

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"
accent_color: #285BB8

# Options
custom_header: false
custom_nav_footer: false
reverse: false
