# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.maxlaumeister.com
title: Maximillian Laumeister
email: max.laumeister@gmail.com
description: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# For Travis CI
exclude: [vendor]

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Resume
    icon: file-text-o
    url: resume/
    targetblank: false
  - title: Linkedin
    icon: linkedin
    url: https://www.linkedin.com/in/maxlaumeister
    targetblank: true
  - title: Github
    icon: github
    url: https://github.com/MaxLaumeister/
    targetblank: true
  - title: Blog
    icon: align-left
    url: http://blog.maxlaumeister.com/
    targetblank: true

# ----------------------------------- #
#   Am I ready to be hired right now  #
#   (i.e. not currently employed)     #
# ----------------------------------- #

readyforwork: no

