# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Maximillian Laumeister
email: max.laumeister@gmail.com
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Resume
    icon: file-text-o
    url: resume/
  - title: Linkedin
    icon: linkedin
    url: https://www.linkedin.com/in/maxlaumeister
  - title: Github
    icon: github
    url: https://github.com/MaxLaumeister/
  - title: Blog
    icon: align-left
    url: http://blog.maxlaumeister.com/

# ----------------------------------- #
#   Am I ready to be hired right now  #
#   (i.e. not currently employed)     #
# ----------------------------------- #

readyforwork: no

