# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.maxlaumeister.com # For index pages
ext_url: https://max-laumeister.appspot.com # For js, css, etc
title: Maximillian Laumeister
email: max.laumeister@gmail.com
description: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# For Travis CI
exclude: [vendor]

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Resume
    icon: file-text-o
    class: resume-button
  - title: Linkedin
    icon: linkedin
    url: https://www.linkedin.com/in/maxlaumeister
    targetblank: true
  - title: Github
    icon: github
    url: https://github.com/MaxLaumeister/
    targetblank: true
  - title: Blog
    icon: align-left
    url: http://blog.maxlaumeister.com/
    targetblank: true
    
# ------------------------- #
#   Jekyll-Assets Plugin    #
# ------------------------- #

assets:
  #
  # Pathname of the destination of generated (bundled) assets relative
  # to the destination of the root.
  #
  dirname: assets
  #
  # Base URL of assets paths.
  #
  #baseurl: assets/
  baseurl: https://max-laumeister.appspot.com/assets/
  #
  # Pathnames where to find assets relative to the root of the site.
  #
  sources:
    - _assets/js
    - _assets/css
    - _assets/img
    - _assets/video
  #
  # Sets JS compressor. No compression by default.
  # Possible variants: 'yui', 'uglifier', nil
  #
  js_compressor: uglifier
  #
  # Sets CSS compressor. No compression by default.
  # Possible variants: 'yui', 'sass', nil
  #
  css_compressor: sass
  #
  # Sets cachebusting policy for generated assets.
  #
  # Possible variants:
  #
  #   none - disables cachebusting
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css
  #
  #   soft - leave filenames as-is, but `?cb=<md5>` suffix for URLs generated
  #          with `asset_path`, `javascript` and `stylesheet`:
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css?cb=4f41243847da693a4f356c0486114bc6
  #
  #   hard - (default) injects cachebusting checksum into processed filename:
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app-4f41243847da693a4f356c0486114bc6.css
  #     output URL:   /assets/javascripts/app-4f41243847da693a4f356c0486114bc6.css
  #
  cachebust: hard
  #
  # Whenever or not cache compiled assets (disabled by default).
  # See `Compilation Cache` section of README for details.
  #
  cache: false
  #
  # Specifies list of MIME types that needs to have gzipped versions.
  # You can set it to `false` to disable gzipping. Only javascripts and
  # stylesheets are gzipped by default.
  #
  gzip: false
  #
  # Does not concatenates files requested by `javascript` and `stylesheet`
  # helpers. Instead outputs multiple files in order they are required.
  # Default: false
  #
  debug: false
  #
  # Configuration version. Used to force cache invalidation.
  # Default: 1
  #
  version: 1

# -------------------------------- #
#   Enable Rocket Thrusters        #
#   (i.e. not currently employed)  #
# -------------------------------- #

readyforwork: yes

